intial pass of first class package

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -1,8 +1,23 @@
-export ZOPEN_STABLE_URL="https://chromium.googlesource.com/v8/v8.git"
-export ZOPEN_STABLE_DEPS="depot_tools zoslib cmake make python gn ninja git comp_clang"
-export ZOPEN_DEV_DEPS="depot_tools zoslib cmake make python gn ninja git comp_clang"
 export ZOPEN_BUILD_LINE="DEV"
+# IGOR: We are not using git to clone this repo.  We use fetch from
+# depot tools to "clone" it.  I'm putting here to bypass checks
+# but is there a better way to do this?
+export ZOPEN_DEV_URL="https://chromium.googlesource.com/v8/v8"
+export ZOPEN_DEV_DEPS="depot_tools zoslib cmake make python gn ninja git comp_clang"
+export ZOPEN_RUNTIME_DEPS="zoslib"
+export ZOPEN_BOOTSTRAP="python"
+# Nothing to configure or build:
+export ZOPEN_CONFIGURE="skip"
+export ZOPEN_MAKE="skip"
+export ZOPEN_INSTALL="zopen_install"
 export ZOPEN_CATEGORIES="development language core"
+
+# Set the python dir after buildenv deps are checked
+zopen_pre_patch() {
+  export ZOPEN_PYTHONDIR=`type python3 | head -1 | sed "s:^.*[ (]/:/:;s:)$::"`
+  export ZOPEN_BOOTSTRAP_OPTS="bootstrap/bootstrap.py --bootstrap-name ${ZOPEN_PYTHONDIR}"
+}
+
 
 zopen_check_results()
 {
@@ -23,3 +38,47 @@ zopen_get_version()
   # Rather than hardcoding the version, obtain the version by running the tool/library
   echo "1.0.0"
 }
+
+# This is called first?
+zopen_init()
+{
+  # Check for python
+  if ! type python3 >/dev/null ; then
+    printError "need python3 venv with packages: httplib2 and six"
+  fi
+
+
+  #python3 -m venv curl_python
+  #. ./curl_python/bin/activate
+  #pip3 install impacket
+
+
+  # Ensure path is correct
+  desired_path="zopen/usr/local/zopen/depot_tools/depot_tools-main"
+
+  if  expr "${PATH}" : ".*${desired_path}.*" 1>/dev/null ; then
+    echo "Good. depot_tools is in path."
+  else
+    echo "Path to depot_tools missing.  Adding it to path.."
+    export PATH=${PATH}:${HOME}/${desired_path}
+  fi
+
+  # depot_tools creates the venv, here we ensure the necessary packages are installed
+  # Activate the path
+  echo "activating the virtual env - venv"
+  . ${ZOPEN_PKGINSTAL}/depot_tools/depot_tools-main//venv/bin/activate
+
+  # Update the virtual env
+  echo "updating the virtual env pip"
+  python -m pip install -U pip
+
+  # Install the necessary requirements
+  pip install -r ${ZOPEN_PKGINSTALL}/depot_tools/depot_tools-main/requirements.txt
+
+  # Using depot_tools disable metrics.
+  # Comment out this line if you wish to participate.
+  gclient metrics --opt-out
+
+
+}
+
